name: SimpleXrayDetector
version: 1.0.1
main: org.example.SimpleXrayDetector
api-version: 1.21.4
description: Simple plugin that make you know, who is using x-ray.
author: brokolnn
commands:
  suspiciousscore:
    description: "Show current suspicious score."
    usage: /suspiciousscore [nickname]
  resetsuspiciousscore:
    description: "Reset someones suspicious score."
    usage: /resetsuspiciousscore [nickname]
  lastdiamond:
    description: "Show time since last dug diamond."
    usage: /lastdiamond [nickname]
permissions:
  simplexraydetector.admin:
    description: "admin."
    default: op